import React, { StrictMode } from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import { Provider } from "react-redux";
import store, { persistor } from "./store";
import { PersistGate } from "redux-persist/integration/react";
import { BrowserRouter } from "react-router-dom";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <PersistGate loading={null} persistor={persistor}>
    <Provider store={store}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </Provider>
  </PersistGate>
);
const test3 = {
  "122-desktop-applications": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "241",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "9",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "162",
      measuredH: "25",
      x: "47",
      y: "22",
      properties: {
        size: "17",
        text: "Desktop Applications",
      },
    },
  ],
  "100-desktop-applications:electron": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "188",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "69",
      measuredW: "65",
      measuredH: "25",
      x: "63",
      y: "8",
      properties: {
        size: "17",
        text: "Electron",
      },
    },
  ],
  "123-bonus-content": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "210",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "11",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "115",
      measuredH: "25",
      x: "58",
      y: "12",
      properties: {
        size: "17",
        text: "Bonus Content",
      },
    },
  ],
  "ext_link:google.com": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "207",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "114",
      measuredH: "25",
      x: "45",
      y: "13",
      properties: {
        size: "17",
        text: "Keep Learning",
      },
    },
  ],
  "101-desktop-applications:tauri": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "188",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "38",
      measuredH: "25",
      x: "75",
      y: "8",
      properties: {
        size: "17",
        text: "Tauri",
      },
    },
  ],
  "102-build-tools:linters-formatters": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "225",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "176",
      measuredH: "25",
      x: "25",
      y: "13",
      properties: {
        size: "17",
        text: "Linters and Formatters",
      },
    },
  ],
  "100-build-tools:linters-formatters:prettier": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "145",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "66",
      measuredW: "58",
      measuredH: "25",
      x: "44",
      y: "7",
      properties: {
        size: "17",
        text: "Prettier",
      },
    },
  ],
  "101-build-tools:linters-formatters:eslint": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "145",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "53",
      measuredW: "51",
      measuredH: "25",
      x: "46",
      y: "7",
      properties: {
        size: "17",
        text: "ESLint",
      },
    },
  ],
  "101-package-managers:yarn": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "151",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "33",
      measuredH: "25",
      x: "66",
      y: "12",
      properties: {
        text: "yarn",
        size: "17",
      },
    },
  ],
  "101-html": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "250",
      h: "55",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "48",
      measuredH: "25",
      x: "101",
      y: "16",
      properties: {
        size: "17",
        text: "HTML",
      },
    },
  ],
  "ext_link:roadmap.sh/frontend": [
    {
      ID: "0",
      typeID: "Label",
      zOrder: "0",
      measuredW: "144",
      measuredH: "40",
      x: "0",
      y: "0",
      properties: {
        size: "32",
        text: "Front-end",
      },
    },
  ],
  "100-html:learn-the-basics": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "296",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "7",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "134",
      measuredW: "128",
      measuredH: "25",
      x: "90",
      y: "15",
      properties: {
        size: "17",
        text: "Learn the basics",
      },
    },
  ],
  "101-html:writing-semantic-html": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "296",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "5",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "189",
      measuredW: "183",
      measuredH: "25",
      x: "63",
      y: "13",
      properties: {
        size: "17",
        text: "Writing Semantic HTML",
      },
    },
  ],
  "102-html:forms-and-validations": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "296",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "5",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "172",
      measuredW: "169",
      measuredH: "25",
      x: "71",
      y: "13",
      properties: {
        size: "17",
        text: "Forms and Validations",
      },
    },
  ],
  "103-html:conventions-and-best-practices": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "296",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "9",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "248",
      measuredW: "246",
      measuredH: "25",
      x: "33",
      y: "17",
      properties: {
        size: "17",
        text: "Conventions and Best Practices",
      },
    },
  ],
  "102-css": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "250",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "33",
      measuredH: "25",
      x: "108",
      y: "14",
      properties: {
        size: "17",
        text: "CSS",
      },
    },
  ],
  "101-css:making-layouts": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "281",
      h: "47",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "4",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "130",
      measuredW: "120",
      measuredH: "25",
      x: "76",
      y: "15",
      properties: {
        size: "17",
        text: "Making Layouts",
      },
    },
  ],
  "100-css:learn-the-basics": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "280",
      h: "43",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "4",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "140",
      measuredW: "128",
      measuredH: "25",
      x: "70",
      y: "13",
      properties: {
        size: "17",
        text: "Learn the basics",
      },
    },
  ],
  "102-css:responsive-design-and-media-queries": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "280",
      h: "43",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "2",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "248",
      measuredW: "246",
      measuredH: "22",
      x: "18",
      y: "12",
      properties: {
        size: "14",
        text: "Responsive design and Media Queries",
      },
    },
  ],
  "103-javascript": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "250",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "81",
      measuredH: "25",
      x: "82",
      y: "13",
      properties: {
        size: "17",
        text: "JavaScript",
      },
    },
  ],
  "100-javascript:syntax-and-basic-constructs": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "296",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "8",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "228",
      measuredW: "219",
      measuredH: "25",
      x: "43",
      y: "16",
      properties: {
        size: "17",
        text: "Syntax and Basic Constructs",
      },
    },
  ],
  "101-javascript:learn-dom-manipulation": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "297",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "5",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "197",
      measuredW: "193",
      measuredH: "25",
      x: "59",
      y: "13",
      properties: {
        size: "17",
        text: "Learn DOM Manipulation",
      },
    },
  ],
  "104-javascript:concepts": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "296",
      h: "113",
      measuredW: "200",
      measuredH: "140",
      x: "9",
      y: "4",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "247",
      measuredW: "246",
      measuredH: "25",
      x: "34",
      y: "49",
      properties: {
        size: "17",
        text: "Hoisting, Event Bubbling, Scope,",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "2",
      w: "245",
      measuredW: "231",
      measuredH: "25",
      x: "36",
      y: "78",
      properties: {
        size: "17",
        text: "Prototype, Shadow DOM, strict",
      },
    },
    {
      ID: "3",
      typeID: "Label",
      zOrder: "3",
      w: "202",
      measuredW: "195",
      measuredH: "25",
      x: "57",
      y: "19",
      properties: {
        size: "17",
        text: "Understand the concepts",
      },
    },
  ],
  "102-javascript:learn-fetch-api-ajax-xhr": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "296",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "5",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "234",
      measuredW: "224",
      measuredH: "25",
      x: "40",
      y: "13",
      properties: {
        size: "17",
        text: "Learn Fetch API / Ajax (XHR)",
      },
    },
  ],
  "103-javascript:es6-and-modular-javascript": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "296",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "9",
      y: "7",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "234",
      measuredW: "228",
      measuredH: "25",
      x: "41",
      y: "15",
      properties: {
        size: "17",
        text: "ES6+ and modular JavaScript",
      },
    },
  ],
  "ext_link:roadmap.sh": [
    {
      ID: "0",
      typeID: "Canvas",
      zOrder: "0",
      w: "320",
      h: "45",
      measuredW: "100",
      measuredH: "70",
      x: "0",
      y: "0",
      properties: {
        borderColor: "4273622",
        color: "4273622",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "105",
      measuredH: "28",
      x: "139",
      y: "8",
      properties: {
        color: "16777215",
        size: "20",
        text: "roadmap.sh",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "2",
      measuredW: "45",
      measuredH: "28",
      x: "65",
      y: "8",
      properties: {
        color: "16777215",
        size: "20",
        text: "https",
      },
    },
    {
      ID: "3",
      typeID: "Label",
      zOrder: "3",
      measuredW: "5",
      measuredH: "28",
      x: "113",
      y: "8",
      properties: {
        bold: "true",
        color: "16777215",
        size: "20",
        text: ":",
      },
    },
    {
      ID: "4",
      typeID: "Label",
      zOrder: "4",
      measuredW: "10",
      measuredH: "28",
      x: "120",
      y: "9",
      properties: {
        color: "16777215",
        size: "20",
        text: "/",
      },
    },
    {
      ID: "5",
      typeID: "Label",
      zOrder: "5",
      measuredW: "10",
      measuredH: "28",
      x: "128",
      y: "9",
      properties: {
        color: "16777215",
        size: "20",
        text: "/",
      },
    },
  ],
  "100-internet": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "178",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "9",
      y: "10",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "62",
      measuredH: "25",
      x: "67",
      y: "23",
      properties: {
        text: "Internet",
        size: "17",
      },
    },
  ],
  "100-internet:how-does-the-internet-work": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "299",
      h: "44",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "9",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "223",
      measuredW: "219",
      measuredH: "25",
      x: "45",
      y: "19",
      properties: {
        size: "17",
        text: "How does the internet work?",
      },
    },
  ],
  "101-internet:what-is-http": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "299",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "7",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "119",
      measuredW: "113",
      measuredH: "25",
      x: "98",
      y: "15",
      properties: {
        size: "17",
        text: "What is HTTP?",
      },
    },
  ],
  "102-internet:browsers-and-how-they-work": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "299",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "8",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "230",
      measuredW: "225",
      measuredH: "25",
      x: "42",
      y: "16",
      properties: {
        size: "17",
        text: "Browsers and how they work?",
      },
    },
  ],
  "103-internet:dns-and-how-it-works": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "280",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "9",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "179",
      measuredW: "175",
      measuredH: "25",
      x: "51",
      y: "17",
      properties: {
        size: "17",
        text: "DNS and how it works?",
      },
    },
  ],
  "104-internet:what-is-domain-name": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "280",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "5",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "189",
      measuredW: "180",
      measuredH: "25",
      x: "51",
      y: "13",
      properties: {
        size: "17",
        text: "What is Domain Name?",
      },
    },
  ],
  "105-internet:what-is-hosting": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "280",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "6",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "133",
      measuredW: "126",
      measuredH: "25",
      x: "74",
      y: "14",
      properties: {
        size: "17",
        text: "What is hosting?",
      },
    },
  ],
  "104-html:accessibility": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "280",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "8",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "101",
      measuredW: "94",
      measuredH: "25",
      x: "89",
      y: "16",
      properties: {
        size: "17",
        text: "Accessibility",
      },
    },
  ],
  "105-html:seo-basics": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "280",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "6",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "94",
      measuredW: "90",
      measuredH: "25",
      x: "93",
      y: "14",
      properties: {
        size: "17",
        text: "SEO Basics",
      },
    },
  ],
  "100-version-control-systems:basic-usage-of-git": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "216",
      h: "54",
      measuredW: "200",
      measuredH: "140",
      x: "9",
      y: "8",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "144",
      measuredH: "25",
      x: "45",
      y: "23",
      properties: {
        text: "Basic Usage of Git",
        size: "17",
      },
    },
  ],
  "100-repo-hosting-services:github": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "230",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "10",
      y: "9",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "54",
      measuredH: "25",
      x: "98",
      y: "22",
      properties: {
        text: "GitHub",
        size: "17",
      },
    },
  ],
  "105-repo-hosting-services": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "352",
      h: "78",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "172",
      measuredH: "25",
      x: "90",
      y: "15",
      properties: {
        text: "Repo hosting services",
        size: "17",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "2",
      w: "279",
      measuredW: "275",
      measuredH: "23",
      x: "32",
      y: "41",
      properties: {
        size: "15",
        text: "Create account and Learn to use GitHub",
      },
    },
  ],
  "104-version-control-systems": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "336",
      h: "77",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "186",
      measuredH: "25",
      x: "75",
      y: "15",
      properties: {
        text: "Version Control Systems",
        size: "17",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "2",
      w: "292",
      measuredW: "285",
      measuredH: "23",
      x: "19",
      y: "40",
      properties: {
        size: "15",
        text: "What are they and why you should use one",
      },
    },
  ],
  "107-package-managers": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "211",
      h: "53",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "149",
      measuredH: "25",
      x: "31",
      y: "14",
      properties: {
        text: "Package Managers",
        size: "17",
      },
    },
  ],
  "100-package-managers:npm": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "151",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "36",
      measuredW: "34",
      measuredH: "25",
      x: "65",
      y: "12",
      properties: {
        size: "17",
        text: "npm",
      },
    },
  ],
  "102-repo-hosting-services:bitbucket": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "230",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "5",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "73",
      measuredH: "25",
      x: "86",
      y: "17",
      properties: {
        color: "3355443",
        text: "Bitbucket",
        size: "17",
      },
    },
  ],
  "101-repo-hosting-services:gitlab": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "230",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "6",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "51",
      measuredH: "25",
      x: "97",
      y: "18",
      properties: {
        color: "3355443",
        size: "17",
        text: "GitLab",
      },
    },
  ],
  "106-web-security-knowledge": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "372",
      h: "54",
      measuredW: "200",
      measuredH: "140",
      x: "9",
      y: "8",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "189",
      measuredH: "25",
      x: "100",
      y: "23",
      properties: {
        text: "Web Security Knowledge",
        size: "17",
      },
    },
  ],
  undefined: [],
  "102-web-security-knowledge:cors": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "163",
      h: "48",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "48",
      measuredH: "25",
      x: "58",
      y: "12",
      properties: {
        text: "CORS",
        size: "17",
      },
    },
  ],
  "100-web-security-knowledge:https": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "166",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "54",
      measuredH: "25",
      x: "56",
      y: "12",
      properties: {
        text: "HTTPS",
        size: "17",
      },
    },
  ],
  "101-web-security-knowledge:content-security-policy": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "257",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "175",
      measuredH: "25",
      x: "41",
      y: "12",
      properties: {
        text: "Content Security Policy",
        size: "17",
      },
    },
  ],
  "103-web-security-knowledge:owasp-security-risks": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "257",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "169",
      measuredH: "25",
      x: "44",
      y: "12",
      properties: {
        text: "OWASP Security Risks",
        size: "17",
      },
    },
  ],
  "109-css-preprocessors": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "216",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "150",
      measuredH: "25",
      x: "33",
      y: "12",
      properties: {
        text: "CSS Preprocessors",
        size: "17",
      },
    },
  ],
  "108-css-architecture": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "213",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "131",
      measuredH: "25",
      x: "41",
      y: "12",
      properties: {
        text: "CSS Architecture",
        size: "17",
      },
    },
  ],
  "100-css-architecture:bem": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "151",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "45",
      measuredW: "38",
      measuredH: "25",
      x: "60",
      y: "8",
      properties: {
        size: "17",
        text: "BEM",
      },
    },
  ],
  "110-build-tools": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "211",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "83",
      measuredH: "25",
      x: "64",
      y: "13",
      properties: {
        size: "17",
        text: "Build Tools",
      },
    },
  ],
  "100-build-tools:task-runners": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "225",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "105",
      measuredH: "25",
      x: "60",
      y: "14",
      properties: {
        size: "17",
        text: "Task Runners",
      },
    },
  ],
  "100-build-tools:task-runners:npm-scripts": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "145",
      h: "45",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "89",
      measuredH: "25",
      x: "24",
      y: "10",
      properties: {
        size: "17",
        text: "npm scripts",
      },
    },
  ],
  "100-build-tools:module-bundlers:webpack": [
    {
      ID: "1",
      typeID: "Label",
      zOrder: "0",
      w: "72",
      measuredW: "72",
      measuredH: "25",
      x: "52",
      y: "7",
      properties: {
        size: "17",
        text: "Webpack",
      },
    },
    {
      ID: "2",
      typeID: "TextArea",
      zOrder: "1",
      w: "148",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "3",
      typeID: "Label",
      zOrder: "2",
      measuredW: "72",
      measuredH: "25",
      x: "42",
      y: "7",
      properties: {
        text: "Webpack",
        size: "17",
      },
    },
  ],
  "102-build-tools:module-bundlers:rollup": [
    {
      ID: "1",
      typeID: "Label",
      zOrder: "0",
      w: "46",
      measuredW: "49",
      measuredH: "25",
      x: "65",
      y: "7",
      properties: {
        size: "17",
        text: "Rollup",
      },
    },
    {
      ID: "2",
      typeID: "TextArea",
      zOrder: "1",
      w: "147",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "3",
      typeID: "Label",
      zOrder: "2",
      w: "63",
      measuredW: "49",
      measuredH: "25",
      x: "55",
      y: "7",
      properties: {
        size: "17",
        text: "Rollup",
      },
    },
  ],
  "103-build-tools:module-bundlers:parcel": [
    {
      ID: "0",
      typeID: "Label",
      zOrder: "0",
      w: "46",
      measuredW: "49",
      measuredH: "25",
      x: "65",
      y: "7",
      properties: {
        size: "17",
        text: "Parcel",
      },
    },
    {
      ID: "1",
      typeID: "TextArea",
      zOrder: "1",
      w: "146",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "2",
      w: "63",
      measuredW: "49",
      measuredH: "25",
      x: "55",
      y: "7",
      properties: {
        size: "17",
        text: "Parcel",
      },
    },
  ],
  "101-build-tools:module-bundlers": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "225",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "131",
      measuredH: "25",
      x: "47",
      y: "13",
      properties: {
        size: "17",
        text: "Module Bundlers",
      },
    },
  ],
  "111-pick-a-framework": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "213",
      h: "53",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "142",
      measuredW: "136",
      measuredH: "25",
      x: "36",
      y: "14",
      properties: {
        size: "17",
        text: "Pick a Framework",
      },
    },
  ],
  "100-pick-a-framework:react-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "145",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "68",
      measuredW: "47",
      measuredH: "25",
      x: "55",
      y: "7",
      properties: {
        size: "17",
        text: "React",
      },
    },
  ],
  "101-pick-a-framework:angular": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "145",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "64",
      measuredW: "59",
      measuredH: "25",
      x: "49",
      y: "7",
      properties: {
        size: "17",
        text: "Angular",
      },
    },
  ],
  "102-pick-a-framework:vue-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "145",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "45",
      measuredH: "25",
      x: "58",
      y: "7",
      properties: {
        text: "Vue.js",
        size: "17",
      },
    },
  ],
  "112-modern-css": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "203",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "98",
      measuredH: "25",
      x: "53",
      y: "13",
      properties: {
        size: "17",
        text: "Modern CSS",
      },
    },
  ],
  "100-modern-css:styled-components": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "202",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "151",
      measuredW: "150",
      measuredH: "25",
      x: "25",
      y: "7",
      properties: {
        size: "17",
        text: "Styled Components",
      },
    },
  ],
  "101-modern-css:css-modules": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "202",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "103",
      measuredW: "103",
      measuredH: "25",
      x: "49",
      y: "7",
      properties: {
        size: "17",
        text: "CSS Modules",
      },
    },
  ],
  "103-modern-css:emotion": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "201",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "64",
      measuredH: "25",
      x: "69",
      y: "7",
      properties: {
        text: "Emotion",
        size: "17",
      },
    },
  ],
  "100-graphql:apollo": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "167",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "49",
      measuredW: "48",
      measuredH: "25",
      x: "58",
      y: "8",
      properties: {
        size: "17",
        text: "Apollo",
      },
    },
  ],
  "120-static-site-generators": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "281",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "9",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "169",
      measuredH: "25",
      x: "56",
      y: "22",
      properties: {
        size: "17",
        text: "Static Site Generators",
      },
    },
  ],
  "101-static-site-generators:gatsbyjs": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "78",
      measuredW: "73",
      measuredH: "25",
      x: "35",
      y: "8",
      properties: {
        size: "17",
        text: "GatsbyJS",
      },
    },
  ],
  "100-static-site-generators:next-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "58",
      measuredW: "52",
      measuredH: "25",
      x: "45",
      y: "8",
      properties: {
        size: "17",
        text: "Next.js",
      },
    },
  ],
  "102-static-site-generators:nuxt-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "56",
      measuredW: "52",
      measuredH: "25",
      x: "46",
      y: "8",
      properties: {
        size: "17",
        text: "Nuxt.js",
      },
    },
  ],
  "103-static-site-generators:vuepress": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "76",
      measuredW: "72",
      measuredH: "25",
      x: "40",
      y: "8",
      properties: {
        size: "17",
        text: "Vuepress",
      },
    },
  ],
  "104-static-site-generators:jekyll": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "49",
      measuredW: "43",
      measuredH: "25",
      x: "52",
      y: "8",
      properties: {
        size: "17",
        text: "Jekyll",
      },
    },
  ],
  "114-css-frameworks": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "212",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "131",
      measuredH: "25",
      x: "40",
      y: "13",
      properties: {
        size: "17",
        text: "CSS Frameworks",
      },
    },
  ],
  "114-css-frameworks:css-first": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "335",
      h: "137",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "14540253",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "1",
      measuredW: "150",
      measuredH: "24",
      x: "154",
      y: "17",
      properties: {
        size: "16",
        text: "CSS first frameworks",
      },
    },
    {
      ID: "3",
      typeID: "Label",
      zOrder: "2",
      measuredW: "145",
      measuredH: "24",
      x: "154",
      y: "44",
      properties: {
        size: "16",
        text: "that don't come with",
      },
    },
    {
      ID: "4",
      typeID: "Label",
      zOrder: "3",
      measuredW: "99",
      measuredH: "24",
      x: "154",
      y: "71",
      properties: {
        size: "16",
        text: "JS framework",
      },
    },
    {
      ID: "5",
      typeID: "Label",
      zOrder: "4",
      measuredW: "166",
      measuredH: "24",
      x: "153",
      y: "98",
      properties: {
        size: "16",
        text: "components by default.",
      },
    },
  ],
  "100-css-frameworks:css-first:bootstrap": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "127",
      h: "52",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "14540253",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "81",
      measuredW: "75",
      measuredH: "25",
      x: "27",
      y: "13",
      properties: {
        size: "17",
        text: "Bootstrap",
      },
    },
  ],
  "101-css-frameworks:css-first:bulma": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "127",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "14540253",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "50",
      measuredW: "49",
      measuredH: "25",
      x: "39",
      y: "12",
      properties: {
        size: "17",
        text: "Bulma",
      },
    },
  ],
  "115-testing-your-apps": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "405",
      h: "158",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "144",
      measuredH: "26",
      x: "125",
      y: "19",
      properties: {
        size: "18",
        text: "Testing your Apps",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "2",
      w: "349",
      measuredW: "328",
      measuredH: "25",
      x: "22",
      y: "86",
      properties: {
        size: "17",
        text: "and {color:blue}Functional{color} tests and learn how to write",
      },
    },
    {
      ID: "3",
      typeID: "Label",
      zOrder: "3",
      w: "302",
      measuredW: "286",
      measuredH: "25",
      x: "21",
      y: "115",
      properties: {
        size: "17",
        text: "them with the tools listed on the right.",
      },
    },
    {
      ID: "4",
      typeID: "Label",
      zOrder: "4",
      w: "362",
      measuredW: "361",
      measuredH: "25",
      x: "21",
      y: "56",
      properties: {
        size: "17",
        text: "Learn the difference between {color:blue}Unit{color}, {color:blue}Integration{color}, ",
      },
    },
  ],
  "101-testing-your-apps:react-testing-library": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "195",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "152",
      measuredH: "25",
      x: "22",
      y: "7",
      properties: {
        text: "react-testing-library",
        size: "17",
      },
    },
  ],
  "100-testing-your-apps:jest": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "194",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "39",
      measuredW: "33",
      measuredH: "25",
      x: "77",
      y: "8",
      properties: {
        size: "17",
        text: "Jest",
      },
    },
  ],
  "102-testing-your-apps:cypress": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "195",
      h: "39",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "63",
      measuredH: "25",
      x: "63",
      y: "7",
      properties: {
        text: "Cypress",
        size: "17",
      },
    },
  ],
  "116-type-checkers": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "226",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "10",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "115",
      measuredH: "25",
      x: "53",
      y: "23",
      properties: {
        size: "17",
        text: "Type Checkers",
      },
    },
  ],
  "100-type-checkers:typescript": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "199",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "7",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "91",
      measuredW: "81",
      measuredH: "25",
      x: "54",
      y: "15",
      properties: {
        size: "17",
        text: "TypeScript",
      },
    },
  ],
  "117-progressive-web-apps": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "241",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "6",
      y: "11",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "172",
      measuredH: "25",
      x: "41",
      y: "24",
      properties: {
        size: "17",
        text: "Progressive Web Apps",
      },
    },
  ],
  "118-server-side-rendering": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "278",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "9",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "225",
      measuredH: "25",
      x: "29",
      y: "22",
      properties: {
        size: "17",
        text: "Server Side Rendering (SSR)",
      },
    },
  ],
  "100-server-side-rendering:react-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "116",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "47",
      measuredH: "25",
      x: "34",
      y: "8",
      properties: {
        text: "React",
        size: "17",
      },
    },
  ],
  "100-server-side-rendering:react-js:next-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "106",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "52",
      measuredH: "25",
      x: "27",
      y: "8",
      properties: {
        size: "17",
        text: "Next.js",
      },
    },
  ],
  "101-server-side-rendering:angular": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "119",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "69",
      measuredW: "59",
      measuredH: "25",
      x: "35",
      y: "8",
      properties: {
        size: "17",
        text: "Angular",
      },
    },
  ],
  "100-server-side-rendering:angular:universal": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "111",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "73",
      measuredW: "72",
      measuredH: "25",
      x: "19",
      y: "8",
      properties: {
        size: "17",
        text: "Universal",
      },
    },
  ],
  "102-server-side-rendering:vue-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "118",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "48",
      measuredW: "45",
      measuredH: "25",
      x: "37",
      y: "8",
      properties: {
        text: "Vue.js",
        size: "17",
      },
    },
  ],
  "100-server-side-rendering:vue-js:nuxt-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "111",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "55",
      measuredW: "52",
      measuredH: "25",
      x: "28",
      y: "8",
      properties: {
        size: "17",
        text: "Nuxt.js",
      },
    },
  ],
  "121-mobile-applications": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "210",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "9",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "169",
      measuredW: "150",
      measuredH: "25",
      x: "27",
      y: "22",
      properties: {
        size: "17",
        text: "Mobile Applications",
      },
    },
  ],
  "100-mobile-applications:react-native": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "9",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "101",
      measuredW: "100",
      measuredH: "25",
      x: "32",
      y: "8",
      properties: {
        size: "17",
        text: "React Native",
      },
    },
  ],
  "101-mobile-applications:nativescript": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "94",
      measuredH: "25",
      x: "27",
      y: "8",
      properties: {
        text: "NativeScript",
        size: "17",
      },
    },
  ],
  "102-mobile-applications:flutter": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "10",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "53",
      measuredW: "50",
      measuredH: "25",
      x: "57",
      y: "8",
      properties: {
        size: "17",
        text: "Flutter",
      },
    },
  ],
  "105-static-site-generators:hugo": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "43",
      measuredW: "42",
      measuredH: "25",
      x: "52",
      y: "8",
      properties: {
        size: "17",
        text: "Hugo",
      },
    },
  ],
  "103-mobile-applications:ionic": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "40",
      measuredW: "38",
      measuredH: "25",
      x: "54",
      y: "8",
      properties: {
        size: "17",
        text: "Ionic",
      },
    },
  ],
  "119-graphql": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "146",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "71",
      measuredH: "25",
      x: "37",
      y: "12",
      properties: {
        size: "17",
        text: "GraphQL",
      },
    },
  ],
  "101-graphql:relay-modern": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "168",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "115",
      measuredW: "107",
      measuredH: "25",
      x: "40",
      y: "8",
      properties: {
        size: "17",
        text: "Relay Modern",
      },
    },
  ],
  "113-web-components": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "230",
      h: "50",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "10",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "137",
      measuredH: "25",
      x: "44",
      y: "23",
      properties: {
        size: "17",
        text: "Web Components",
      },
    },
  ],
  "100-web-components:html-templates": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "190",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "132",
      measuredW: "131",
      measuredH: "25",
      x: "30",
      y: "7",
      properties: {
        size: "17",
        text: "HTML Templates",
      },
    },
  ],
  "101-web-components:custom-elements": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "190",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "139",
      measuredW: "136",
      measuredH: "25",
      x: "30",
      y: "7",
      properties: {
        size: "17",
        text: "Custom Elements",
      },
    },
  ],
  "102-web-components:shadow-dom": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "190",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "105",
      measuredW: "105",
      measuredH: "25",
      x: "38",
      y: "7",
      properties: {
        size: "17",
        text: "Shadow DOM",
      },
    },
  ],
  "101-css-preprocessors:postcss": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "146",
      h: "43",
      measuredW: "200",
      measuredH: "140",
      x: "10",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "74",
      measuredW: "66",
      measuredH: "25",
      x: "49",
      y: "9",
      properties: {
        size: "17",
        text: "PostCSS",
      },
    },
  ],
  "100-css-preprocessors:sass": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "146",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "10",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "46",
      measuredW: "37",
      measuredH: "25",
      x: "60",
      y: "8",
      properties: {
        size: "17",
        text: "Sass",
      },
    },
  ],
  "102-modern-css:styled-jsx": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "201",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      w: "90",
      measuredW: "80",
      measuredH: "25",
      x: "56",
      y: "7",
      properties: {
        size: "17",
        text: "Styled JSX",
      },
    },
  ],
  "101-build-tools:module-bundlers:esbuild": [
    {
      ID: "1",
      typeID: "Label",
      zOrder: "0",
      w: "72",
      measuredW: "72",
      measuredH: "25",
      x: "52",
      y: "7",
      properties: {
        size: "17",
        text: "Webpack",
      },
    },
    {
      ID: "2",
      typeID: "TextArea",
      zOrder: "1",
      w: "149",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "3",
      typeID: "Label",
      zOrder: "2",
      measuredW: "55",
      measuredH: "25",
      x: "50",
      y: "7",
      properties: {
        size: "17",
        text: "esbuild",
      },
    },
  ],
  "104-build-tools:module-bundlers:vite": [
    {
      ID: "0",
      typeID: "Label",
      zOrder: "0",
      w: "46",
      measuredW: "49",
      measuredH: "25",
      x: "65",
      y: "7",
      properties: {
        size: "17",
        text: "Parcel",
      },
    },
    {
      ID: "1",
      typeID: "TextArea",
      zOrder: "1",
      w: "151",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "2",
      measuredW: "30",
      measuredH: "25",
      x: "53",
      y: "7",
      properties: {
        size: "17",
        text: "Vite",
      },
    },
  ],
  "107-static-site-generators:eleventy": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
        align: "center",
        size: "17",
      },
    },
    {
      ID: "3",
      typeID: "Label",
      zOrder: "3",
      measuredW: "66",
      measuredH: "25",
      x: "41",
      y: "8",
      properties: {
        text: "Eleventy",
        size: "17",
      },
    },
  ],
  "102-package-managers:pnpm": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "151",
      h: "49",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "44",
      measuredH: "25",
      x: "61",
      y: "12",
      properties: {
        size: "17",
        text: "pnpm",
      },
    },
  ],
  "103-pick-a-framework:svelte": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "145",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "48",
      measuredH: "25",
      x: "58",
      y: "7",
      properties: {
        size: "17",
        text: "Svelte",
      },
    },
  ],
  "104-pick-a-framework:solid-js": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "145",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "7",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "61",
      measuredH: "25",
      x: "58",
      y: "7",
      properties: {
        size: "17",
        text: "Solid JS",
      },
    },
  ],
  "104-testing-your-apps:playwright": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "197",
      h: "39",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "78",
      measuredH: "25",
      x: "60",
      y: "7",
      properties: {
        size: "17",
        text: "Playwright",
      },
    },
  ],
  "101-server-side-rendering:react-js:remix": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "106",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "49",
      measuredH: "25",
      x: "28",
      y: "8",
      properties: {
        size: "17",
        text: "Remix",
      },
    },
  ],
  "103-static-site-generators:remix": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "148",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "49",
      measuredH: "25",
      x: "49",
      y: "8",
      properties: {
        size: "17",
        text: "Remix",
      },
    },
  ],
  "102-desktop-applications:flutter": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "188",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "50",
      measuredH: "25",
      x: "69",
      y: "8",
      properties: {
        size: "17",
        text: "Flutter",
      },
    },
  ],
  "106-static-site-generators:astro": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "147",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "39",
      measuredH: "25",
      x: "54",
      y: "8",
      properties: {
        size: "17",
        text: "Astro",
      },
    },
  ],
  "103-server-side-rendering:svelte": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "119",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "48",
      measuredH: "25",
      x: "36",
      y: "7",
      properties: {
        size: "17",
        text: "Svelte",
      },
    },
  ],
  "100-server-side-rendering:svelte:svelte-kit": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "111",
      h: "41",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16770457",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "73",
      measuredH: "25",
      x: "17",
      y: "8",
      properties: {
        size: "17",
        text: "Svelte Kit",
      },
    },
  ],
  "116-auth-strategies": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "401",
      h: "87",
      measuredW: "200",
      measuredH: "140",
      x: "10",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "227",
      measuredH: "28",
      x: "97",
      y: "16",
      properties: {
        size: "20",
        text: "Authentication Strategies",
      },
    },
    {
      ID: "4",
      typeID: "Label",
      zOrder: "4",
      measuredW: "353",
      measuredH: "25",
      x: "34",
      y: "46",
      properties: {
        size: "17",
        text: "JWT, OAuth, SSO, Basic Auth, Session Auth etc",
      },
    },
  ],
  "114-css-frameworks:js-first": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "333",
      h: "228",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "263",
      measuredH: "24",
      x: "19",
      y: "163",
      properties: {
        size: "16",
        text: "JS based and better to use with your",
      },
    },
    {
      ID: "2",
      typeID: "Label",
      zOrder: "2",
      measuredW: "247",
      measuredH: "24",
      x: "19",
      y: "189",
      properties: {
        size: "16",
        text: "framework based JavaScript apps.",
      },
    },
  ],
  "100-css-frameworks:js-first:tailwind-css": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "136",
      h: "40",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "61",
      measuredH: "25",
      x: "37",
      y: "7",
      properties: {
        size: "17",
        text: "Tailwind",
      },
    },
  ],
  "102-css-frameworks:js-first:material-ui": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "137",
      h: "37",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "86",
      measuredH: "25",
      x: "26",
      y: "6",
      properties: {
        size: "17",
        text: "Material UI",
      },
    },
  ],
  "104-css-frameworks:js-first:mantine": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "149",
      h: "39",
      measuredW: "200",
      measuredH: "140",
      x: "8",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "63",
      measuredH: "25",
      x: "51",
      y: "7",
      properties: {
        size: "17",
        text: "Mantine",
      },
    },
  ],
  "103-css-frameworks:js-first:radix-ui": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "139",
      h: "37",
      measuredW: "200",
      measuredH: "140",
      x: "0",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "66",
      measuredH: "25",
      x: "34",
      y: "6",
      properties: {
        size: "17",
        text: "Radix UI",
      },
    },
  ],
  "101-css-frameworks:js-first:chakra-ui": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "152",
      h: "39",
      measuredW: "200",
      measuredH: "140",
      x: "9",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "78",
      measuredH: "25",
      x: "44",
      y: "8",
      properties: {
        size: "17",
        text: "Chakra UI",
      },
    },
  ],
  "105-css-frameworks:js-first:daisy-ui": [
    {
      ID: "0",
      typeID: "TextArea",
      zOrder: "0",
      w: "152",
      h: "39",
      measuredW: "200",
      measuredH: "140",
      x: "9",
      y: "0",
      properties: {
        color: "16776960",
      },
    },
    {
      ID: "1",
      typeID: "Label",
      zOrder: "1",
      measuredW: "60",
      measuredH: "25",
      x: "55",
      y: "8",
      properties: {
        size: "17",
        text: "DaisyUI",
      },
    },
  ],
  "100-progressive-web-apps:storage": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "78",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        text: "Storage",
        size: "18",
      },
    },
  ],
  "101-progressive-web-apps:web-sockets": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "120",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        text: "Web Sockets",
        size: "18",
      },
    },
  ],
  "102-progressive-web-apps:server-sent-events": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "170",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        text: "Server Sent Events",
        size: "18",
      },
    },
  ],
  "103-progressive-web-apps:service-workers": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "147",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        text: "Service Workers",
        size: "18",
      },
    },
  ],
  "104-progressive-web-apps:location": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "84",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16770457",
        text: "Location",
        size: "18",
      },
    },
  ],
  "105-progressive-web-apps:notifications": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "115",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16770457",
        text: "Notifications",
        size: "18",
      },
    },
  ],
  "106-progressive-web-apps:device-orientation": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "167",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16770457",
        text: "Device Orientation",
        size: "18",
      },
    },
  ],
  "107-progressive-web-apps:payments": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "94",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16770457",
        text: "Payments",
        size: "18",
      },
    },
  ],
  "108-progressive-web-apps:credentials": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "192",
      measuredW: "108",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16770457",
        text: "Credentials",
        size: "18",
      },
    },
  ],
  "109-progressive-web-apps:prpl-pattern": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "225",
      measuredW: "124",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        size: "18",
        text: "PRPL Pattern",
      },
    },
  ],
  "110-progressive-web-apps:rail-model": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "225",
      measuredW: "110",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        size: "18",
        text: "RAIL Model",
      },
    },
  ],
  "111-progressive-web-apps:performance-metrics": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "225",
      measuredW: "185",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        size: "18",
        text: "Performance Metrics",
      },
    },
  ],
  "112-progressive-web-apps:lighthouse": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "225",
      measuredW: "156",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        size: "18",
        text: "Using Lighthouse",
      },
    },
  ],
  "113-progressive-web-apps:browser-devtools": [
    {
      ID: "0",
      typeID: "TextInput",
      zOrder: "0",
      w: "225",
      measuredW: "141",
      measuredH: "32",
      x: "0",
      y: "0",
      properties: {
        align: "center",
        color: "16776960",
        size: "18",
        text: "Using DevTools",
      },
    },
  ],
};
